### ISSUE TITLE
Week numbering when generating followup accross multiple years

### ISSUE THREAD

**Issue by victornoel** [albinscode/atgenerator#4]
I tried to generate a followup from December 2016 to end of January 2017 and I noticed that the first week of 2017 was numbered 0.

I don't think this is normal :)

**Comment by albinscode** [comment]
Due to my bad usage of moment.js library.
I was in 'en' locale and was substracting 1 week to end the year 2016 with 52 weeks instead of 53. Obviously the next week (first of 2017) was at 0.

The solution is to use locally the 'fr' locale (to avoid any other side effects):
` date.locale('fr').weeks()`

In test.
